#' Plot Trait Correlations Across Environments with Labels
#'
#' @param blup_data The 'blups' dataframe generated by model_traits().
#' @param trait_x String. The trait to plot on the x-axis.
#' @param trait_y String. The trait to plot on the y-axis.
#' @param envs Character vector (Optional). Specific environments to plot.
#' @param good_gens Character vector (Optional). Genotypes to highlight in green.
#' @param bad_gens Character vector (Optional). Genotypes to highlight in red.
#'
#' @return A ggplot object with a faceted scatterplot.
#' @export
#' @importFrom dplyr filter select mutate case_when arrange
#' @importFrom tidyr pivot_wider drop_na
#' @importFrom ggplot2 ggplot aes geom_point geom_smooth facet_wrap scale_color_manual scale_size_manual scale_alpha_manual theme_minimal labs theme element_text
#' @importFrom ggrepel geom_text_repel
plot_trait_correlations <- function(blup_data, trait_x, trait_y, envs = NULL, good_gens = NULL, bad_gens = NULL) {

  # 1. Filter Data
  plot_df <- blup_data |>
    dplyr::filter(Trait %in% c(trait_x, trait_y))

  if (!is.null(envs)) {
    plot_df <- plot_df |> dplyr::filter(Environment %in% envs)
  }

  available_traits <- unique(plot_df$Trait)
  if (!(trait_x %in% available_traits) || !(trait_y %in% available_traits)) {
    stop("One or both traits not found in the data.")
  }

  # 2. Pivot to Wide Format
  plot_wide <- plot_df |>
    dplyr::select(Genotype, Environment, Trait, Predicted) |>
    tidyr::pivot_wider(names_from = Trait, values_from = Predicted) |>
    tidyr::drop_na(dplyr::all_of(c(trait_x, trait_y)))

  if (nrow(plot_wide) == 0) stop("No overlapping data points.")

  # 3. Create Highlight Categories and Labels
  plot_wide <- plot_wide |>
    dplyr::mutate(
      Highlight = dplyr::case_when(
        Genotype %in% good_gens ~ "Good",
        Genotype %in% bad_gens ~ "Bad",
        TRUE ~ "Normal"
      ),
      Is_Highlighted = Highlight != "Normal",
      # NEW: Create label text ONLY for highlighted points
      Label_Text = ifelse(Is_Highlighted, as.character(Genotype), "")
    ) |>
    dplyr::arrange(Is_Highlighted)

  # 4. Generate the Plot
  p <- ggplot2::ggplot(plot_wide, ggplot2::aes(x = .data[[trait_x]], y = .data[[trait_y]])) +

    # Trend line
    ggplot2::geom_smooth(method = "lm", color = "gray40", fill = "gray80", linetype = "dashed", alpha = 0.3) +

    # Points
    ggplot2::geom_point(ggplot2::aes(color = Highlight, size = Is_Highlighted, alpha = Is_Highlighted)) +

    # NEW: Add Repelled Labels
    # We map color to Highlight so the text matches the point color
    ggrepel::geom_text_repel(
      ggplot2::aes(label = Label_Text, color = Highlight),
      size = 3.5,             # Adjust font size
      fontface = "bold",      # Make them pop
      box.padding = 0.5,      # Space around text
      point.padding = 0.3,    # Space around points
      max.overlaps = Inf,     # Try to force labeling all highlighted points
      show.legend = FALSE     # Don't clutter the legend with text symbols
    ) +

    # Scales
    ggplot2::scale_color_manual(
      values = c("Good" = "forestgreen", "Bad" = "firebrick", "Normal" = "gray70"),
      breaks = c("Good", "Bad", "Normal")
    ) +
    ggplot2::scale_size_manual(values = c("TRUE" = 3, "FALSE" = 1.5), guide = "none") +
    ggplot2::scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.6), guide = "none") +

    # Faceting and Theme
    ggplot2::facet_wrap(~Environment, scales = "free") +
    ggplot2::theme_minimal() +
    ggplot2::labs(
      title = paste("Correlation:", trait_y, "vs", trait_x),
      subtitle = "BLUPs with highlighted genotypes labeled",
      x = trait_x,
      y = trait_y,
      color = "Genotype Status"
    ) +
    ggplot2::theme(
      strip.text = ggplot2::element_text(face = "bold", size = 11),
      legend.position = "bottom"
    )

  return(p)
}
